layout_spectrum: 0.8852298
color:
  saturation: 0.9355047
  brandStrength: 0
  lightness: 0.4727061
  rhythmicContrast: 0.9778342
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.8795111
name: Newlife
